#!/bin/bash
# Stage 3: Enter chroot and build the final system.
#
# Mounts virtual filesystems, chroots into $LFS, then runs the inner build
# script which compiles the final passes of binutils, gcc, and all base
# packages — this time with the just-built temp tools, ending at a fully
# self-hosted aarch64 LFS userspace.
#
# Follows LFS book chapter 7-8.

set -euo pipefail

REPO_ROOT=${REPO_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}

require_root() { [ "$(id -u)" = 0 ] || { echo "needs root for mount + chroot" >&2; exit 1; }; }
require_root

# Bind-mount kernel virtual filesystems
mount -v --bind  /dev    "$LFS/dev"
mount -vt devpts devpts -o gid=5,mode=0620 "$LFS/dev/pts"
mount -vt proc   proc    "$LFS/proc"
mount -vt sysfs  sysfs   "$LFS/sys"
mount -vt tmpfs  tmpfs   "$LFS/run"
[ -h "$LFS/dev/shm" ] && install -v -d -m 1777 "$LFS$(realpath /dev/shm)" || mount -t tmpfs -o nosuid,nodev tmpfs "$LFS/dev/shm"

cleanup() {
  set +e
  mountpoint -q "$LFS/dev/pts" && umount "$LFS/dev/pts"
  mountpoint -q "$LFS/dev/shm" && umount "$LFS/dev/shm"
  mountpoint -q "$LFS/dev"     && umount "$LFS/dev"
  mountpoint -q "$LFS/run"     && umount "$LFS/run"
  mountpoint -q "$LFS/proc"    && umount "$LFS/proc"
  mountpoint -q "$LFS/sys"     && umount "$LFS/sys"
}
trap cleanup EXIT

# Stage the inner build script + repo into the chroot
mkdir -p "$LFS/repo"
cp -a "$REPO_ROOT/." "$LFS/repo/"

# Pre-resolve all package versions/URLs on the builder side (we have jq) so
# the in-chroot inner script can use plain shell variables — jq isn't built
# into temp-tools and we don't want to bring host binaries into the rootfs.
# Bash variable names can't contain '-', so package keys get s/-/_/g.
MANIFEST_JSON="$REPO_ROOT/tools/manifest.json"
{
  echo "# Auto-generated by 03-chroot.sh from tools/manifest.json"
  for k in binutils gcc glibc linux_headers; do
    v=$(jq -r ".toolchain.$k.version // empty" "$MANIFEST_JSON")
    u=$(jq -r ".toolchain.$k.url // empty" "$MANIFEST_JSON")
    [ -n "$v" ] && echo "ver_$k=$v"
    [ -n "$u" ] && echo "url_$k=$u"
  done
  for k in gmp mpfr mpc isl; do
    v=$(jq -r ".toolchain.gcc_prereqs.$k.version" "$MANIFEST_JSON")
    u=$(jq -r ".toolchain.gcc_prereqs.$k.url" "$MANIFEST_JSON")
    echo "ver_$k=$v"; echo "url_$k=$u"
  done
  echo "ver_kernel=$(jq -r .kernel.version "$MANIFEST_JSON")"
  echo "url_kernel=$(jq -r .kernel.url "$MANIFEST_JSON")"
  for section in base_packages init_and_session bootloader; do
    # `to_entries[] | select(.value|type=="object") | .key` skips the
    # documentation keys like "$slackware_parity_note" / "$logrotate_stack_note"
    # that ship as string values inside otherwise-object-only sections. Same
    # guard pattern as tools/fetch-sources.sh (PR #24) and
    # scripts/lint/manifest-schema.sh — without it, the inner indexer trips
    # on the first string key with "Cannot index string with string 'version'".
    for k in $(jq -r ".$section | to_entries[] | select(.value|type==\"object\") | .key" "$MANIFEST_JSON"); do
      bash_k=${k//-/_}
      v=$(jq -r ".$section.\"$k\".version" "$MANIFEST_JSON")
      u=$(jq -r ".$section.\"$k\".url" "$MANIFEST_JSON")
      echo "ver_$bash_k=$v"; echo "url_$bash_k=$u"
    done
  done
} > "$LFS/repo/versions.env"

# Compile-time hardening (ADR-011): pre-render the flag sets + per-package
# exclusions into hardening.env. The chroot doesn't have jq, so 03b sources
# this file plus the helper (which detects HARDENING_*_CFLAGS already set
# and skips its jq path).
. "$REPO_ROOT/images/gnunix-base/lib/hardening.sh"
hardening_render_env "$LFS/repo/hardening.env"

chroot "$LFS" /usr/bin/env -i \
  HOME=/root TERM="$TERM" \
  PS1='(lfs chroot) \u:\w\$ ' \
  PATH=/usr/bin:/usr/sbin \
  REPO_ROOT=/repo \
  /bin/bash --login /repo/images/gnunix-base/stages/03b-chroot-inner.sh

echo "[chroot] inner build complete"
